#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_othello")]
	public partial class EntidadesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertFicha(Ficha instance);
    partial void UpdateFicha(Ficha instance);
    partial void DeleteFicha(Ficha instance);
    partial void InsertJugador(Jugador instance);
    partial void UpdateJugador(Jugador instance);
    partial void DeleteJugador(Jugador instance);
    partial void InsertPartida(Partida instance);
    partial void UpdatePartida(Partida instance);
    partial void DeletePartida(Partida instance);
    partial void InsertPartida_Jugador(Partida_Jugador instance);
    partial void UpdatePartida_Jugador(Partida_Jugador instance);
    partial void DeletePartida_Jugador(Partida_Jugador instance);
    partial void InsertTablero(Tablero instance);
    partial void UpdateTablero(Tablero instance);
    partial void DeleteTablero(Tablero instance);
    partial void InsertTablero_Ficha(Tablero_Ficha instance);
    partial void UpdateTablero_Ficha(Tablero_Ficha instance);
    partial void DeleteTablero_Ficha(Tablero_Ficha instance);
    partial void InsertTipo_partida(Tipo_partida instance);
    partial void UpdateTipo_partida(Tipo_partida instance);
    partial void DeleteTipo_partida(Tipo_partida instance);
    #endregion
		
		public EntidadesDataContext() : 
				base(global::modelo.Properties.Settings.Default.db_othelloConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EntidadesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EntidadesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EntidadesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EntidadesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Ficha> Ficha
		{
			get
			{
				return this.GetTable<Ficha>();
			}
		}
		
		public System.Data.Linq.Table<Jugador> Jugador
		{
			get
			{
				return this.GetTable<Jugador>();
			}
		}
		
		public System.Data.Linq.Table<Partida> Partida
		{
			get
			{
				return this.GetTable<Partida>();
			}
		}
		
		public System.Data.Linq.Table<Partida_Jugador> Partida_Jugador
		{
			get
			{
				return this.GetTable<Partida_Jugador>();
			}
		}
		
		public System.Data.Linq.Table<Tablero> Tablero
		{
			get
			{
				return this.GetTable<Tablero>();
			}
		}
		
		public System.Data.Linq.Table<Tablero_Ficha> Tablero_Ficha
		{
			get
			{
				return this.GetTable<Tablero_Ficha>();
			}
		}
		
		public System.Data.Linq.Table<Tipo_partida> Tipo_partida
		{
			get
			{
				return this.GetTable<Tipo_partida>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ficha")]
	public partial class Ficha : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_ficha;
		
		private string _Color;
		
		private int _No_fila;
		
		private int _No_columna;
		
		private EntitySet<Tablero_Ficha> _Tablero_Ficha;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_fichaChanging(int value);
    partial void OnId_fichaChanged();
    partial void OnColorChanging(string value);
    partial void OnColorChanged();
    partial void OnNo_filaChanging(int value);
    partial void OnNo_filaChanged();
    partial void OnNo_columnaChanging(int value);
    partial void OnNo_columnaChanged();
    #endregion
		
		public Ficha()
		{
			this._Tablero_Ficha = new EntitySet<Tablero_Ficha>(new Action<Tablero_Ficha>(this.attach_Tablero_Ficha), new Action<Tablero_Ficha>(this.detach_Tablero_Ficha));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_ficha", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_ficha
		{
			get
			{
				return this._Id_ficha;
			}
			set
			{
				if ((this._Id_ficha != value))
				{
					this.OnId_fichaChanging(value);
					this.SendPropertyChanging();
					this._Id_ficha = value;
					this.SendPropertyChanged("Id_ficha");
					this.OnId_fichaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Color", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string Color
		{
			get
			{
				return this._Color;
			}
			set
			{
				if ((this._Color != value))
				{
					this.OnColorChanging(value);
					this.SendPropertyChanging();
					this._Color = value;
					this.SendPropertyChanged("Color");
					this.OnColorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No_fila", DbType="Int NOT NULL")]
		public int No_fila
		{
			get
			{
				return this._No_fila;
			}
			set
			{
				if ((this._No_fila != value))
				{
					this.OnNo_filaChanging(value);
					this.SendPropertyChanging();
					this._No_fila = value;
					this.SendPropertyChanged("No_fila");
					this.OnNo_filaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No_columna", DbType="Int NOT NULL")]
		public int No_columna
		{
			get
			{
				return this._No_columna;
			}
			set
			{
				if ((this._No_columna != value))
				{
					this.OnNo_columnaChanging(value);
					this.SendPropertyChanging();
					this._No_columna = value;
					this.SendPropertyChanged("No_columna");
					this.OnNo_columnaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ficha_Tablero_Ficha", Storage="_Tablero_Ficha", ThisKey="Id_ficha", OtherKey="Id_ficha")]
		public EntitySet<Tablero_Ficha> Tablero_Ficha
		{
			get
			{
				return this._Tablero_Ficha;
			}
			set
			{
				this._Tablero_Ficha.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tablero_Ficha(Tablero_Ficha entity)
		{
			this.SendPropertyChanging();
			entity.Ficha = this;
		}
		
		private void detach_Tablero_Ficha(Tablero_Ficha entity)
		{
			this.SendPropertyChanging();
			entity.Ficha = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Jugador")]
	public partial class Jugador : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Usuario;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private string _Contraseña;
		
		private System.DateTime _Fecha_nac;
		
		private string _Correo;
		
		private string _Pais;
		
		private EntitySet<Partida_Jugador> _Partida_Jugador;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUsuarioChanging(string value);
    partial void OnUsuarioChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellidoChanging(string value);
    partial void OnApellidoChanged();
    partial void OnContraseñaChanging(string value);
    partial void OnContraseñaChanged();
    partial void OnFecha_nacChanging(System.DateTime value);
    partial void OnFecha_nacChanged();
    partial void OnCorreoChanging(string value);
    partial void OnCorreoChanged();
    partial void OnPaisChanging(string value);
    partial void OnPaisChanged();
    #endregion
		
		public Jugador()
		{
			this._Partida_Jugador = new EntitySet<Partida_Jugador>(new Action<Partida_Jugador>(this.attach_Partida_Jugador), new Action<Partida_Jugador>(this.detach_Partida_Jugador));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this.OnUsuarioChanging(value);
					this.SendPropertyChanging();
					this._Usuario = value;
					this.SendPropertyChanged("Usuario");
					this.OnUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this.OnApellidoChanging(value);
					this.SendPropertyChanging();
					this._Apellido = value;
					this.SendPropertyChanged("Apellido");
					this.OnApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contraseña", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Contraseña
		{
			get
			{
				return this._Contraseña;
			}
			set
			{
				if ((this._Contraseña != value))
				{
					this.OnContraseñaChanging(value);
					this.SendPropertyChanging();
					this._Contraseña = value;
					this.SendPropertyChanged("Contraseña");
					this.OnContraseñaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_nac", DbType="Date NOT NULL")]
		public System.DateTime Fecha_nac
		{
			get
			{
				return this._Fecha_nac;
			}
			set
			{
				if ((this._Fecha_nac != value))
				{
					this.OnFecha_nacChanging(value);
					this.SendPropertyChanging();
					this._Fecha_nac = value;
					this.SendPropertyChanged("Fecha_nac");
					this.OnFecha_nacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this.OnCorreoChanging(value);
					this.SendPropertyChanging();
					this._Correo = value;
					this.SendPropertyChanged("Correo");
					this.OnCorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pais", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Pais
		{
			get
			{
				return this._Pais;
			}
			set
			{
				if ((this._Pais != value))
				{
					this.OnPaisChanging(value);
					this.SendPropertyChanging();
					this._Pais = value;
					this.SendPropertyChanged("Pais");
					this.OnPaisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Jugador_Partida_Jugador", Storage="_Partida_Jugador", ThisKey="Usuario", OtherKey="Usuario")]
		public EntitySet<Partida_Jugador> Partida_Jugador
		{
			get
			{
				return this._Partida_Jugador;
			}
			set
			{
				this._Partida_Jugador.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Partida_Jugador(Partida_Jugador entity)
		{
			this.SendPropertyChanging();
			entity.Jugador = this;
		}
		
		private void detach_Partida_Jugador(Partida_Jugador entity)
		{
			this.SendPropertyChanging();
			entity.Jugador = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Partida")]
	public partial class Partida : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_partida;
		
		private int _Id_tipo;
		
		private int _Id_tablero;
		
		private EntitySet<Partida_Jugador> _Partida_Jugador;
		
		private EntityRef<Tablero> _Tablero;
		
		private EntityRef<Tipo_partida> _Tipo_partida;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_partidaChanging(int value);
    partial void OnId_partidaChanged();
    partial void OnId_tipoChanging(int value);
    partial void OnId_tipoChanged();
    partial void OnId_tableroChanging(int value);
    partial void OnId_tableroChanged();
    #endregion
		
		public Partida()
		{
			this._Partida_Jugador = new EntitySet<Partida_Jugador>(new Action<Partida_Jugador>(this.attach_Partida_Jugador), new Action<Partida_Jugador>(this.detach_Partida_Jugador));
			this._Tablero = default(EntityRef<Tablero>);
			this._Tipo_partida = default(EntityRef<Tipo_partida>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_partida", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_partida
		{
			get
			{
				return this._Id_partida;
			}
			set
			{
				if ((this._Id_partida != value))
				{
					this.OnId_partidaChanging(value);
					this.SendPropertyChanging();
					this._Id_partida = value;
					this.SendPropertyChanged("Id_partida");
					this.OnId_partidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_tipo", DbType="Int NOT NULL")]
		public int Id_tipo
		{
			get
			{
				return this._Id_tipo;
			}
			set
			{
				if ((this._Id_tipo != value))
				{
					if (this._Tipo_partida.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_tipoChanging(value);
					this.SendPropertyChanging();
					this._Id_tipo = value;
					this.SendPropertyChanged("Id_tipo");
					this.OnId_tipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_tablero", DbType="Int NOT NULL")]
		public int Id_tablero
		{
			get
			{
				return this._Id_tablero;
			}
			set
			{
				if ((this._Id_tablero != value))
				{
					if (this._Tablero.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_tableroChanging(value);
					this.SendPropertyChanging();
					this._Id_tablero = value;
					this.SendPropertyChanged("Id_tablero");
					this.OnId_tableroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Partida_Partida_Jugador", Storage="_Partida_Jugador", ThisKey="Id_partida", OtherKey="Id_partida")]
		public EntitySet<Partida_Jugador> Partida_Jugador
		{
			get
			{
				return this._Partida_Jugador;
			}
			set
			{
				this._Partida_Jugador.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tablero_Partida", Storage="_Tablero", ThisKey="Id_tablero", OtherKey="Id_tablero", IsForeignKey=true)]
		public Tablero Tablero
		{
			get
			{
				return this._Tablero.Entity;
			}
			set
			{
				Tablero previousValue = this._Tablero.Entity;
				if (((previousValue != value) 
							|| (this._Tablero.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tablero.Entity = null;
						previousValue.Partida.Remove(this);
					}
					this._Tablero.Entity = value;
					if ((value != null))
					{
						value.Partida.Add(this);
						this._Id_tablero = value.Id_tablero;
					}
					else
					{
						this._Id_tablero = default(int);
					}
					this.SendPropertyChanged("Tablero");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tipo_partida_Partida", Storage="_Tipo_partida", ThisKey="Id_tipo", OtherKey="Id_tipo", IsForeignKey=true)]
		public Tipo_partida Tipo_partida
		{
			get
			{
				return this._Tipo_partida.Entity;
			}
			set
			{
				Tipo_partida previousValue = this._Tipo_partida.Entity;
				if (((previousValue != value) 
							|| (this._Tipo_partida.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tipo_partida.Entity = null;
						previousValue.Partida.Remove(this);
					}
					this._Tipo_partida.Entity = value;
					if ((value != null))
					{
						value.Partida.Add(this);
						this._Id_tipo = value.Id_tipo;
					}
					else
					{
						this._Id_tipo = default(int);
					}
					this.SendPropertyChanged("Tipo_partida");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Partida_Jugador(Partida_Jugador entity)
		{
			this.SendPropertyChanging();
			entity.Partida = this;
		}
		
		private void detach_Partida_Jugador(Partida_Jugador entity)
		{
			this.SendPropertyChanging();
			entity.Partida = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Partida_Jugador")]
	public partial class Partida_Jugador : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_partida_jugador;
		
		private int _Id_partida;
		
		private string _Usuario;
		
		private EntityRef<Partida> _Partida;
		
		private EntityRef<Jugador> _Jugador;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_partida_jugadorChanging(int value);
    partial void OnId_partida_jugadorChanged();
    partial void OnId_partidaChanging(int value);
    partial void OnId_partidaChanged();
    partial void OnUsuarioChanging(string value);
    partial void OnUsuarioChanged();
    #endregion
		
		public Partida_Jugador()
		{
			this._Partida = default(EntityRef<Partida>);
			this._Jugador = default(EntityRef<Jugador>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_partida_jugador", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_partida_jugador
		{
			get
			{
				return this._Id_partida_jugador;
			}
			set
			{
				if ((this._Id_partida_jugador != value))
				{
					this.OnId_partida_jugadorChanging(value);
					this.SendPropertyChanging();
					this._Id_partida_jugador = value;
					this.SendPropertyChanged("Id_partida_jugador");
					this.OnId_partida_jugadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_partida", DbType="Int NOT NULL")]
		public int Id_partida
		{
			get
			{
				return this._Id_partida;
			}
			set
			{
				if ((this._Id_partida != value))
				{
					if (this._Partida.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_partidaChanging(value);
					this.SendPropertyChanging();
					this._Id_partida = value;
					this.SendPropertyChanged("Id_partida");
					this.OnId_partidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					if (this._Jugador.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUsuarioChanging(value);
					this.SendPropertyChanging();
					this._Usuario = value;
					this.SendPropertyChanged("Usuario");
					this.OnUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Partida_Partida_Jugador", Storage="_Partida", ThisKey="Id_partida", OtherKey="Id_partida", IsForeignKey=true)]
		public Partida Partida
		{
			get
			{
				return this._Partida.Entity;
			}
			set
			{
				Partida previousValue = this._Partida.Entity;
				if (((previousValue != value) 
							|| (this._Partida.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Partida.Entity = null;
						previousValue.Partida_Jugador.Remove(this);
					}
					this._Partida.Entity = value;
					if ((value != null))
					{
						value.Partida_Jugador.Add(this);
						this._Id_partida = value.Id_partida;
					}
					else
					{
						this._Id_partida = default(int);
					}
					this.SendPropertyChanged("Partida");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Jugador_Partida_Jugador", Storage="_Jugador", ThisKey="Usuario", OtherKey="Usuario", IsForeignKey=true)]
		public Jugador Jugador
		{
			get
			{
				return this._Jugador.Entity;
			}
			set
			{
				Jugador previousValue = this._Jugador.Entity;
				if (((previousValue != value) 
							|| (this._Jugador.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Jugador.Entity = null;
						previousValue.Partida_Jugador.Remove(this);
					}
					this._Jugador.Entity = value;
					if ((value != null))
					{
						value.Partida_Jugador.Add(this);
						this._Usuario = value.Usuario;
					}
					else
					{
						this._Usuario = default(string);
					}
					this.SendPropertyChanged("Jugador");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tablero")]
	public partial class Tablero : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_tablero;
		
		private int _No_fichas_blancas;
		
		private int _No_fichas_negras;
		
		private EntitySet<Partida> _Partida;
		
		private EntitySet<Tablero_Ficha> _Tablero_Ficha;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_tableroChanging(int value);
    partial void OnId_tableroChanged();
    partial void OnNo_fichas_blancasChanging(int value);
    partial void OnNo_fichas_blancasChanged();
    partial void OnNo_fichas_negrasChanging(int value);
    partial void OnNo_fichas_negrasChanged();
    #endregion
		
		public Tablero()
		{
			this._Partida = new EntitySet<Partida>(new Action<Partida>(this.attach_Partida), new Action<Partida>(this.detach_Partida));
			this._Tablero_Ficha = new EntitySet<Tablero_Ficha>(new Action<Tablero_Ficha>(this.attach_Tablero_Ficha), new Action<Tablero_Ficha>(this.detach_Tablero_Ficha));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_tablero", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_tablero
		{
			get
			{
				return this._Id_tablero;
			}
			set
			{
				if ((this._Id_tablero != value))
				{
					this.OnId_tableroChanging(value);
					this.SendPropertyChanging();
					this._Id_tablero = value;
					this.SendPropertyChanged("Id_tablero");
					this.OnId_tableroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No_fichas_blancas", DbType="Int NOT NULL")]
		public int No_fichas_blancas
		{
			get
			{
				return this._No_fichas_blancas;
			}
			set
			{
				if ((this._No_fichas_blancas != value))
				{
					this.OnNo_fichas_blancasChanging(value);
					this.SendPropertyChanging();
					this._No_fichas_blancas = value;
					this.SendPropertyChanged("No_fichas_blancas");
					this.OnNo_fichas_blancasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No_fichas_negras", DbType="Int NOT NULL")]
		public int No_fichas_negras
		{
			get
			{
				return this._No_fichas_negras;
			}
			set
			{
				if ((this._No_fichas_negras != value))
				{
					this.OnNo_fichas_negrasChanging(value);
					this.SendPropertyChanging();
					this._No_fichas_negras = value;
					this.SendPropertyChanged("No_fichas_negras");
					this.OnNo_fichas_negrasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tablero_Partida", Storage="_Partida", ThisKey="Id_tablero", OtherKey="Id_tablero")]
		public EntitySet<Partida> Partida
		{
			get
			{
				return this._Partida;
			}
			set
			{
				this._Partida.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tablero_Tablero_Ficha", Storage="_Tablero_Ficha", ThisKey="Id_tablero", OtherKey="Id_tablero")]
		public EntitySet<Tablero_Ficha> Tablero_Ficha
		{
			get
			{
				return this._Tablero_Ficha;
			}
			set
			{
				this._Tablero_Ficha.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Partida(Partida entity)
		{
			this.SendPropertyChanging();
			entity.Tablero = this;
		}
		
		private void detach_Partida(Partida entity)
		{
			this.SendPropertyChanging();
			entity.Tablero = null;
		}
		
		private void attach_Tablero_Ficha(Tablero_Ficha entity)
		{
			this.SendPropertyChanging();
			entity.Tablero = this;
		}
		
		private void detach_Tablero_Ficha(Tablero_Ficha entity)
		{
			this.SendPropertyChanging();
			entity.Tablero = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tablero_Ficha")]
	public partial class Tablero_Ficha : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_partida_jugador;
		
		private int _Id_tablero;
		
		private int _Id_ficha;
		
		private EntityRef<Ficha> _Ficha;
		
		private EntityRef<Tablero> _Tablero;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_partida_jugadorChanging(int value);
    partial void OnId_partida_jugadorChanged();
    partial void OnId_tableroChanging(int value);
    partial void OnId_tableroChanged();
    partial void OnId_fichaChanging(int value);
    partial void OnId_fichaChanged();
    #endregion
		
		public Tablero_Ficha()
		{
			this._Ficha = default(EntityRef<Ficha>);
			this._Tablero = default(EntityRef<Tablero>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_partida_jugador", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_partida_jugador
		{
			get
			{
				return this._Id_partida_jugador;
			}
			set
			{
				if ((this._Id_partida_jugador != value))
				{
					this.OnId_partida_jugadorChanging(value);
					this.SendPropertyChanging();
					this._Id_partida_jugador = value;
					this.SendPropertyChanged("Id_partida_jugador");
					this.OnId_partida_jugadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_tablero", DbType="Int NOT NULL")]
		public int Id_tablero
		{
			get
			{
				return this._Id_tablero;
			}
			set
			{
				if ((this._Id_tablero != value))
				{
					if (this._Tablero.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_tableroChanging(value);
					this.SendPropertyChanging();
					this._Id_tablero = value;
					this.SendPropertyChanged("Id_tablero");
					this.OnId_tableroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_ficha", DbType="Int NOT NULL")]
		public int Id_ficha
		{
			get
			{
				return this._Id_ficha;
			}
			set
			{
				if ((this._Id_ficha != value))
				{
					if (this._Ficha.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_fichaChanging(value);
					this.SendPropertyChanging();
					this._Id_ficha = value;
					this.SendPropertyChanged("Id_ficha");
					this.OnId_fichaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ficha_Tablero_Ficha", Storage="_Ficha", ThisKey="Id_ficha", OtherKey="Id_ficha", IsForeignKey=true)]
		public Ficha Ficha
		{
			get
			{
				return this._Ficha.Entity;
			}
			set
			{
				Ficha previousValue = this._Ficha.Entity;
				if (((previousValue != value) 
							|| (this._Ficha.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ficha.Entity = null;
						previousValue.Tablero_Ficha.Remove(this);
					}
					this._Ficha.Entity = value;
					if ((value != null))
					{
						value.Tablero_Ficha.Add(this);
						this._Id_ficha = value.Id_ficha;
					}
					else
					{
						this._Id_ficha = default(int);
					}
					this.SendPropertyChanged("Ficha");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tablero_Tablero_Ficha", Storage="_Tablero", ThisKey="Id_tablero", OtherKey="Id_tablero", IsForeignKey=true)]
		public Tablero Tablero
		{
			get
			{
				return this._Tablero.Entity;
			}
			set
			{
				Tablero previousValue = this._Tablero.Entity;
				if (((previousValue != value) 
							|| (this._Tablero.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tablero.Entity = null;
						previousValue.Tablero_Ficha.Remove(this);
					}
					this._Tablero.Entity = value;
					if ((value != null))
					{
						value.Tablero_Ficha.Add(this);
						this._Id_tablero = value.Id_tablero;
					}
					else
					{
						this._Id_tablero = default(int);
					}
					this.SendPropertyChanged("Tablero");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tipo_partida")]
	public partial class Tipo_partida : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_tipo;
		
		private string _tipo;
		
		private EntitySet<Partida> _Partida;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_tipoChanging(int value);
    partial void OnId_tipoChanged();
    partial void OntipoChanging(string value);
    partial void OntipoChanged();
    #endregion
		
		public Tipo_partida()
		{
			this._Partida = new EntitySet<Partida>(new Action<Partida>(this.attach_Partida), new Action<Partida>(this.detach_Partida));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_tipo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_tipo
		{
			get
			{
				return this._Id_tipo;
			}
			set
			{
				if ((this._Id_tipo != value))
				{
					this.OnId_tipoChanging(value);
					this.SendPropertyChanging();
					this._Id_tipo = value;
					this.SendPropertyChanged("Id_tipo");
					this.OnId_tipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				if ((this._tipo != value))
				{
					this.OntipoChanging(value);
					this.SendPropertyChanging();
					this._tipo = value;
					this.SendPropertyChanged("tipo");
					this.OntipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tipo_partida_Partida", Storage="_Partida", ThisKey="Id_tipo", OtherKey="Id_tipo")]
		public EntitySet<Partida> Partida
		{
			get
			{
				return this._Partida;
			}
			set
			{
				this._Partida.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Partida(Partida entity)
		{
			this.SendPropertyChanging();
			entity.Tipo_partida = this;
		}
		
		private void detach_Partida(Partida entity)
		{
			this.SendPropertyChanging();
			entity.Tipo_partida = null;
		}
	}
}
#pragma warning restore 1591
